trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: |
      docker-compose build
      ./scripts/ci-run-test.sh
    displayName: 'Run unitest and coverage'


- job: 'Build'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
 
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
 
  - script: python setup.py sdist
    displayName: 'Build sdist'
 
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/dist
      targetFolder: $(Build.ArtifactStagingDirectory)
 
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: dist
