# Generated by Django 2.1.4 on 2019-02-11 16:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtailapiimagerendition.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailapiimagerendition', '0001_initial'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtailapiimagerendition.blocks.ImageWithRenditionsChooserBlock(required=False)), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('100x50', '100 x 50'), ('100x200', '100 x 200'), ('150x150', '150 x 150')], label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('400x200', '400 x 200'), ('400x800', '400 x 800'), ('600x600', '600 x 600')], label='Desktop Rendition'))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeaderImageCustomPage',
            fields=[
                ('imagewithrenditions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailapiimagerendition.ImageWithRenditions')),
                ('custom_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_image', to='dummy_page.CustomPage')),
            ],
            bases=('wagtailapiimagerendition.imagewithrenditions',),
        ),
    ]
