# Generated by Django 2.1.7 on 2019-03-20 12:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtailapiimagerendition.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailapiimagerendition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImageTestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_mobile_rendition', models.CharField(choices=[('none', 'Use Original'), ('100x50', '100 x 50'), ('100x200', '100 x 200'), ('150x150', '150 x 150')], default='none', max_length=10, verbose_name='Mobile Rendition')),
                ('image_desktop_rendition', models.CharField(choices=[('none', 'Use Original'), ('400x200', '400 x 200'), ('400x800', '400 x 800'), ('600x600', '600 x 600')], default='none', max_length=10, verbose_name='Desktop Rendition')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailapiimagerendition.CustomImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtailapiimagerendition.blocks.ImageWithRenditionsChooserBlock(required=False)), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('100x50', '100 x 50'), ('100x200', '100 x 200'), ('150x150', '150 x 150')], classname='wasm-meta-field', label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('400x200', '400 x 200'), ('400x800', '400 x 800'), ('600x600', '600 x 600')], classname='wasm-meta-field', label='Desktop Rendition'))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='headerimagetestpage',
            name='test_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_image', to='test_page.TestPage'),
        ),
    ]
