# Generated by Django 2.1.7 on 2019-04-30 11:19

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailapiimagerendition.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('test_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerimagetestpage',
            name='image_desktop_rendition',
            field=models.CharField(choices=[('none', 'Use Original'), ('400x200', '400 x 200'), ('400x800', '400 x 800'), ('600x600', '600 x 600'), ('601x601', '601 x 601')], default='none', max_length=10, verbose_name='Desktop Rendition'),
        ),
        migrations.AlterField(
            model_name='headerimagetestpage',
            name='image_mobile_rendition',
            field=models.CharField(choices=[('none', 'Use Original'), ('100x50', '100 x 50'), ('100x200', '100 x 200'), ('150x150', '150 x 150'), ('151x151', '151 x 151')], default='none', max_length=10, verbose_name='Mobile Rendition'),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtailapiimagerendition.blocks.ImageWithRenditionsChooserBlock(required=False)), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('100x50', '100 x 50'), ('100x200', '100 x 200'), ('150x150', '150 x 150'), ('151x151', '151 x 151')], classname='wasm-meta-field', label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('400x200', '400 x 200'), ('400x800', '400 x 800'), ('600x600', '600 x 600'), ('601x601', '601 x 601')], classname='wasm-meta-field', label='Desktop Rendition'))]))], blank=True, null=True),
        ),
    ]
